name       : signon-kwallet-extension
version    : 19.04.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.0/src/signon-kwallet-extension-19.04.0.tar.xz : eb93120d2acfbac4b823bc301b3724d250dc7e7041eef347c1337c7df84c0c40
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
