name       : signon-kwallet-extension
version    : 19.12.3
release    : 23
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.3/src/signon-kwallet-extension-19.12.3.tar.xz : 46199be023bad630b769b14c2c0a63feff2949da944c76780b1ebd9a50ee3daa
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
