name       : signon-kwallet-extension
version    : 20.12.0
release    : 32
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/signon-kwallet-extension-20.12.0.tar.xz : 7019c1b9b42930c2b0ab197674eeb435eccf6fef2aeda8b87a989479b1ee1e2e
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
