name       : signon-kwallet-extension
version    : 18.04.1
release    : 1
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.1/src/signon-kwallet-extension-18.04.1.tar.xz : 2bd29ede45295f3a67c94d2ef9db1e3b7cddb5316c4a7fcd8f1c18dc03541b76
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
