name       : signon-kwallet-extension
version    : 19.08.1
release    : 17
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/signon-kwallet-extension-19.08.1.tar.xz : 7d558509cf015641c76d4203c8dadc4e9720278fb39b4561eb2bce4e5412bb83
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
