name       : signon-kwallet-extension
version    : 18.04.3
release    : 3
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/signon-kwallet-extension-18.04.3.tar.xz : cd99f0e13a7d3b6c9e22cd3a60731dcc624a810c33042667af28f80f1c051db9
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
