name       : signon-kwallet-extension
version    : 19.04.1
release    : 13
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.1/src/signon-kwallet-extension-19.04.1.tar.xz : 658bbae2534896e13a7aced654f38164130ee3c748349d044000d0d7dcaa1c38
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
