name       : signon-kwallet-extension
version    : 23.04.3
release    : 57
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/signon-kwallet-extension-23.04.3.tar.xz : 74735f639497ae5aa11d18f3037d293d18acf817b19770b7b82167bd6ba3f418
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
