name       : signon-kwallet-extension
version    : 18.12.1
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.1/src/signon-kwallet-extension-18.12.1.tar.xz : 5680d4010fcfb98b3a0152fe7a5d3bf2fd0830d9cb756d15d6eeea3cdaf71b05
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
