name       : signon-kwallet-extension
version    : 18.08.1
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/signon-kwallet-extension-18.08.1.tar.xz : 6432e7ca277d85db6a1ccc6a9306dbc52f2a845d9c5ccbf92e16fb2e9debc9f1
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
