name       : signon-kwallet-extension
version    : 21.12.3
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/signon-kwallet-extension-21.12.3.tar.xz : 7579e0434114c33eb5fea3f232bbd414658e2715f3f3a3a220a4f5be4079606b
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
