name       : signon-kwallet-extension
version    : 21.08.3
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/signon-kwallet-extension-21.08.3.tar.xz : 96aa05bacea3f8c0551a3e19ba02e8f4960fcf19b290ffa5d56472daacf77cd4
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
