name       : signon-kwallet-extension
version    : 18.08.3
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.3/src/signon-kwallet-extension-18.08.3.tar.xz : 7dadb09bf6072ba7b9ad8e000badfba9180b37b4bfeb661f00f96fd9d6026828
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
