name       : signon-kwallet-extension
version    : 20.08.3
release    : 31
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.3/src/signon-kwallet-extension-20.08.3.tar.xz : 311c8cd1fb1f1214286a4213b6010c5e751122c6f2e6cec324030bae12f61ae8
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
