name       : signon-kwallet-extension
version    : 18.12.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/signon-kwallet-extension-18.12.0.tar.xz : 1ae19fb82870c31a6077c5c39976b8abd4f37a41586709fdc391f015b6e7f547
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
