name       : signon-kwallet-extension
version    : 19.04.2
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.2/src/signon-kwallet-extension-19.04.2.tar.xz : 70f99d0c3b2351bc865456676839a7632b1cc5566f477a2e611857f12095a0ba
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
