name       : signon-kwallet-extension
version    : 22.04.2
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/signon-kwallet-extension-22.04.2.tar.xz : 81db99f9f301a8de6bc09265744f1f10c9e3a7ea79daff69f7798e8c4379564c
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
