name       : signon-kwallet-extension
version    : 21.08.2
release    : 43
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/signon-kwallet-extension-21.08.2.tar.xz : 9af3a61f9b73174b37828501912aeeec02bfc8f9323dff5adb9e42dc133457a6
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
