name       : signon-kwallet-extension
version    : 19.12.0
release    : 20
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.0/src/signon-kwallet-extension-19.12.0.tar.xz : 663659b125aafff56f7777cf55e1ba22256cc66a89b5a1d97658ce75ad777c96
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
