name       : signon-kwallet-extension
version    : 18.04.2
release    : 2
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.2/src/signon-kwallet-extension-18.04.2.tar.xz : 7c019cf8ec8cc84718335d18d95be0ccab9664c725879acabccbabebf3ad56e0
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
