name       : signon-kwallet-extension
version    : 22.04.0
release    : 48
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/signon-kwallet-extension-22.04.0.tar.xz : 33d19b1b758a21e568ce508cc168e568e34716f148cd83e214fb8a3f3194d2e8
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
