name       : signon-kwallet-extension
version    : 21.12.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/signon-kwallet-extension-21.12.0.tar.xz : bd49fb147f3b96e162e94130c16950d58b806ae0f47025994a4b77eeb4ae0a29
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
