name       : signon-kwallet-extension
version    : 22.04.3
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/signon-kwallet-extension-22.04.3.tar.xz : a19088f8dc538d1ce13faa1acd6508fbb8fe80ad666b255bfda7a721a74fba6e
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
