name       : signon-kwallet-extension
version    : 20.04.1
release    : 25
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.1/src/signon-kwallet-extension-20.04.1.tar.xz : 1ce6c80522ccf281035c3ec5a45e6a9cd4577ecaf9355d9f04b533b1df946e5d
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
