name       : signon-kwallet-extension
version    : 23.04.0
release    : 54
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/signon-kwallet-extension-23.04.0.tar.xz : 07c9dbe4470d8cd4e1b81661138ea2adbcd5077ec99203445d27257ddb2de8fb
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
