name       : signon-kwallet-extension
version    : 19.08.2
release    : 18
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/signon-kwallet-extension-19.08.2.tar.xz : 2521cd2c4f25717f5caf9915474f75614be7dec7053f1e94c1429fac7045cc29
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
