name       : signon-kwallet-extension
version    : 19.12.1
release    : 21
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.1/src/signon-kwallet-extension-19.12.1.tar.xz : a98397cc15733b9c1010f022a8d6bcf7727c4065ba6ae662273ba97864836bbe
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
