name       : signon-kwallet-extension
version    : 21.12.1
release    : 46
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/signon-kwallet-extension-21.12.1.tar.xz : b3f7e76e230dee1785a3e54ab37ff4e5860167b6d0a2c339f553dbc867884226
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : programming
summary    : KWallet integration for signon framework
description: |
    KWallet integration for signon framework.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(SignOnExtension)
    - extra-cmake-modules
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
